// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ead2dbRepeat;

namespace ead2dbRepeat.Migrations
{
    [DbContext(typeof(ForecastContext))]
    partial class ForecastContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ead2dbRepeat.Forecast", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maxTemp")
                        .HasColumnType("int");

                    b.Property<int>("minTemp")
                        .HasColumnType("int");

                    b.Property<string>("tomorrowForecast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("wSpeed")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Forecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
